version: "3.8"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    expose:
      - 9000
    volumes:
      - .:/usr/src/app
      - ./public:/usr/src/app/public
    networks:
      - app_network

  webserver:
    container_name: webserver
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./public:/usr/src/app/public
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    environment:
      NGINX_FPM_HOST: app
      NGINX_ROOT: /usr/src/app/public
    networks:
      - app_network

  caching:
    container_name: caching
    image: redis:latest
    command: redis-server --appendonly yes --replica-read-only no --requirepass redispass
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379
    networks:
      - app_network

networks:
  app_network:
    driver: bridge